GET http://localhost:5029/games

###
GET http://localhost:5029/games/1

###
POST http://localhost:5029/games
Content-Type: application/json

{
    "name": " Turbo",
    "genreId": 3,
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5029/games/1
Content-Type: application/json

{
  "name": "Minecraft V21111",
  "genreId": 1,
  "price": 9.99,
  "releaseDate": "2011-11-18"
}

###
DELETE http://localhost:5029/games/3